### ISSUE TITLE
Bug: Logixlysia incorrectly labels ESLint as a dependency, instead it should be a devDependency.

### ISSUE THREAD

**Issue by SwanX1** [PunGrumpy/logixlysia#46]
- [X] I have checked the latest version.

### Priority

💤 Low

### Description

All ESLint dependencies are installed alongside logixlysia unnecessarily.

### Steps to Reproduce

Simply run `bun i logixlysia`.

### Expected Behavior

Installing Logixlysia should not also install ESLint.

### Possible fix

Moving all ESLint-adjacent dependencies to `devDependencies` in the package.json should work.

**Comment by PunGrumpy** [comment]
Thank you for bringing this issue to our attention 💯

**Comment by PunGrumpy** [comment]
@SwanX1 I released latest-version at https://github.com/PunGrumpy/logixlysia/releases/tag/v3.3.1
