### ISSUE TITLE
Bug: Incorrect Path in buildLogMessage

### ISSUE THREAD

**Issue by Gerhardt0011** [PunGrumpy/logixlysia#48]
### Latest Version Checked

- [X] I have checked the latest version.

### Platform

🍎 macOS

### Priority

🔥 Critical

### Description

```Markdown
Imports are prefixed with "~" so /utils and /types are not able to be resolved.

Incorrect: 

import { LogData, LogLevel, Options, RequestInfo, StoreData } from './types'
import durationString from '~/utils/duration'
import logString from '~/utils/log'
import methodString from '~/utils/method'
import pathString from '~/utils/path'
import statusString from '~/utils/status'
```

Corrected:
```
import { LogData, LogLevel, Options, RequestInfo, StoreData } from '../types'
import durationString from '../utils/duration'
import logString from '../utils/log'
import methodString from '../utils/method'
import pathString from '../utils/path'
import statusString from '../utils/status'
``
```

### Steps to Reproduce

```Markdown
Update to version 3.3.1
```

### Expected Behavior

```Markdown
Import paths to resolve correctly
```

### Actual Behavior

```Markdown
error: Cannot find module "~/utils/duration"
```

### Reproduction Repository

```Markdown
https://github.com/PunGrumpy/logixlysia/blob/main/src/logger/buildLogMessage.ts
```

**Comment by PunGrumpy** [comment]
What happens to it 😵‍💫?! I configured the `tsconfig.json` file to include the necessary path to use `~` as an alias, and it works fine on my setup.

Here's my configuration [tsconfig.json](https://github.com/PunGrumpy/logixlysia/blob/main/tsconfig.json)

```json
...
"paths": {
  "~/*": ["./src/*"]
 },
 ...
 ```

**Comment by Gerhardt0011** [comment]
@PunGrumpy I've noticed that the alias was setup in your TSConfig so this is quite odd.

```bash
bun run dev
$ bun run --hot src/index.ts
error: Cannot find module "~/utils/duration" from "###/node_modules/logixlysia/src/logger/buildLogMessage.ts"
```

Issue still persist after restarting TS Server, I will investigate a bit further.

**Comment by PunGrumpy** [comment]
I knowwwwwwwwwwwwww!! I accidentally ignored `tsconfig.json` in `.npmignore`. I'll try to fix it.

**Comment by PunGrumpy** [comment]
@Gerhardt0011 Okay, it works!! Thanks for bringing up this issue.
