### ISSUE TITLE
Feature: Add a custom transporter to put logs to our DB

### ISSUE THREAD

**Issue by JasonReonardo** [PunGrumpy/logixlysia#51]
### Priority

Critical 🔥

### Title

Add a transporter which takes a function that put them on DB or whatever

### Description

Add a transporter like (winston)[https://www.npmjs.com/package/winston#transports] 
**it's nothing but a function that transfers the log somewhere else like in a database or Kafka etc...**

**Comment by PunGrumpy** [comment]
@JasonReonardo Sorry for late this feature! You can check this function in Logixlysia in version `3.6.0`
