### ISSUE TITLE
Feature: More customizeable timestamp

### ISSUE THREAD

**Issue by caturbgs** [PunGrumpy/logixlysia#69]
### Priority

Medium 🚧

### Title

Add options to format the timestamp output

### Description

```Markdown
Currently, the output timestamp is constrained to only `YYYY-MM-DD HH:mm:ss` format, it will be good to be customized the timestamp order formatting.
```

### Additional Information

```Markdown
My example is like pino-pretty config options `translateTime` https://github.com/pinojs/pino-pretty?tab=readme-ov-file#cli-arguments
```

**Comment by PunGrumpy** [comment]
Hi @caturbgs👋! I added new feature to [v4.0.0](https://github.com/PunGrumpy/logixlysia/releases/) ✨

**Comment by caturbgs** [comment]
> Hi @caturbgs👋! I added new feature to [v4.0.0](https://github.com/PunGrumpy/logixlysia/releases/) ✨
> 
> PS. Sorry for delay, I was busy with other projects 😓

All good mate! The update is so great! Thanks for hearing the feedback.

**Comment by PunGrumpy** [comment]
You're welcome 💘
